# 04. 카운트 기반의 단어 표현(Count based word Representation)

# 1) 다양한 단어의 표현 방법

## 단어의 표현 방법

**국소 표현(Local Representation)** <br/>
해당 단어 그 자체만 보고, 특정값을 맵핑하여 단어를 표현하는 방법<br/>
국소 표현 방법은 단어의 의미, 뉘앙스를 표현할 수 없음 <br/>
이산 표현(Discrete Representation)이라 부르기도 함 <br/>
예시 - puppy(강아지), cute(귀여운), lovely(사랑스러운)라는 각 단어에 1, 2, 3 등과 같은 숫자를 맵핑(mapping)하여 의미를 부여함 <br/>
**one-hot Vector, N-gram, Bag of Words(DTM)** 등이 이에 속함


**분산 표현(Distributed Representation)**  <br/>
해당 단어를 표현하고자 주변을 참고하여 단어를 표현하는 방법 <br/>
분산 표현 방법은 단어의 뉘앙스를 표현할 수 있음 <br/>
연속 표현(Continuous Represnetation)이라 부르기도 함 <br/>
예시 - 해당 단어를 표현하기 위해 주변 단어를 참고함 <br/>
        puppy(강아지)라는 단어 근처에는 주로 cute, lovely 단어가 자주 등장하므로, puppy라는 단어는 cute, lovely한 느낌이다로 단어를 정의함 <br/>
**Word2Vec, FastText, LSA, Glove** 등이 이에 속함
        
        

# 2) Bag of Words(BoW)

## Bag of Words란?

Bag of Words는 단어들의 순서는 전혀 고려하지 않고, 단어들의 출현 빈도(frequency)에만 집중하여 텍스트 데이터의 수치화하는 방법이다. <br/>
Bag of Words를 직역하면 단어들이 들어있는 가방이라는 의미이다.   <br/>
단어들은 가방안에서 섞이기 때문에 순서는 더 이상 중요하지 않다. <br/>
해당 문서 내에서 특정 단어가 N번 등장했다면, 이 가방에는 그 특정 단어가 N개 있게 된다. <br/>

**BoW를 만드는 과정** <br/>
(1) 우선, 각 단어에 고유한 정수 인덱스를 부여한다. <br/>
(2) 각 인덱스의 위치에 단어 토큰의 등장 횟수를 기록한 벡터를 만든다.<br/>

In [5]:
from konlpy.tag import Okt
import re  

okt=Okt()  

# 정규 표현식을 통해 해당 텍스트에서 온점을 제거함
token=re.sub("(\.)","","정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")  

# OKT 형태소 분석기를 통해 토큰화 작업을 수행한 뒤에, token에다가 넣는다
token=okt.morphs(token)  
token

word2index={}  
bow=[]  
for voca in token:  
         if voca not in word2index.keys():  
             word2index[voca]=len(word2index)  
# token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘긴다  
             bow.insert(len(word2index)-1,1)
# BoW 전체에 전부 기본값 1을 넣어줍니다. 단어의 개수는 최소 1개 이상이기 때문 
         else:
            index=word2index.get(voca)
# 재등장하는 단어의 인덱스를 받아온다
            bow[index]=bow[index]+1
# 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다

In [6]:
print(word2index) 

{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}


In [7]:
bow

[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]

## Bag of Words의 다른 예제들

In [8]:
string = '소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.'
token=re.sub("(\.)","",string)  

token=okt.morphs(token)  

word2index={}  
bow=[]  
for voca in token:  
         if voca not in word2index.keys():  
             word2index[voca]=len(word2index)  
             bow.insert(len(word2index)-1,1)
         else:
            index=word2index.get(voca)
            bow[index]=bow[index]+1
            
print(word2index)
print(bow)

{'소비자': 0, '는': 1, '주로': 2, '소비': 3, '하는': 4, '상품': 5, '을': 6, '기준': 7, '으로': 8, '물가상승률': 9, '느낀다': 10}
[1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1]


In [14]:
string = '정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다. 소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.'
token=re.sub("(\.)","",string)  
print('정규화 >>>', token)

token=okt.morphs(token)  
print('token >>>', token)

word2index={}  
bow=[]  

for voca in token:  
         if voca not in word2index.keys():  
             word2index[voca]=len(word2index)  
             bow.insert(len(word2index)-1,1)
         else:
            index=word2index.get(voca)
            bow[index]=bow[index]+1
            
print(word2index)
print(bow)

정규화 >>> 정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다 소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다
token >>> ['정부', '가', '발표', '하는', '물가상승률', '과', '소비자', '가', '느끼는', '물가상승률', '은', '다르다', '소비자', '는', '주로', '소비', '하는', '상품', '을', '기준', '으로', '물가상승률', '을', '느낀다']
{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9, '는': 10, '주로': 11, '소비': 12, '상품': 13, '을': 14, '기준': 15, '으로': 16, '느낀다': 17}
[1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1]


## CountVectorizer 클래스로 BoW 만들기

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()

print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [31]:
text = '주의할 것은 CountVectorizer는 단지 띄어쓰기만을 기준으로 단어를 자르는 낮은 수준의 토큰화를 진행하고 BoW를 만든다는 점입니다. 이는 영어의 경우 띄어쓰기만으로 토큰화가 수행되기 때문에 문제가 없지만 한국어에 CountVectorizer를 적용하면, 조사 등의 이유로 제대로 BoW가 만들어지지 않음을 의미합니다.'

okt = Okt()
ls_text = okt.nouns(text)
string = ' '.join(ls_text)

text_vectorizer = CountVectorizer()
print(text_vectorizer.fit_transform([string]).toarray())   # 리스트에 싸인 문자열을 입력
print(text_vectorizer.vocabulary_)

[[1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1]]
{'주의': 15, '단지': 3, '띄어쓰기': 5, '기준': 1, '단어': 2, '수준': 7, '토큰': 17, '진행': 16, '영어': 9, '경우': 0, '화가': 19, '수행': 8, '때문': 4, '문제': 6, '한국어': 18, '적용': 12, '조사': 14, '이유': 11, '제대로': 13, '의미': 10}


## 불용어를 제거한 BoW 만들기

- 사용자가 직접 정의한 불용어 사용

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])

print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


- CounterVectorizer에서 제공하는 자체 불용어 사용

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")

print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


- NLTK에서 지원하는 불용어 사용

In [35]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Dojun
[nltk_data]     Park\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

text=["Family is not an important thing. It's everything."]

from nltk.corpus import stopwords

sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)

print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [39]:
sw_english = stopwords.words('english')

print(sw_english)
print(len(sw_english))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [40]:
sw_german = stopwords.words('german')

print(sw_german)
print(len(sw_german))

['aber', 'alle', 'allem', 'allen', 'aller', 'alles', 'als', 'also', 'am', 'an', 'ander', 'andere', 'anderem', 'anderen', 'anderer', 'anderes', 'anderm', 'andern', 'anderr', 'anders', 'auch', 'auf', 'aus', 'bei', 'bin', 'bis', 'bist', 'da', 'damit', 'dann', 'der', 'den', 'des', 'dem', 'die', 'das', 'dass', 'daß', 'derselbe', 'derselben', 'denselben', 'desselben', 'demselben', 'dieselbe', 'dieselben', 'dasselbe', 'dazu', 'dein', 'deine', 'deinem', 'deinen', 'deiner', 'deines', 'denn', 'derer', 'dessen', 'dich', 'dir', 'du', 'dies', 'diese', 'diesem', 'diesen', 'dieser', 'dieses', 'doch', 'dort', 'durch', 'ein', 'eine', 'einem', 'einen', 'einer', 'eines', 'einig', 'einige', 'einigem', 'einigen', 'einiger', 'einiges', 'einmal', 'er', 'ihn', 'ihm', 'es', 'etwas', 'euer', 'eure', 'eurem', 'euren', 'eurer', 'eures', 'für', 'gegen', 'gewesen', 'hab', 'habe', 'haben', 'hat', 'hatte', 'hatten', 'hier', 'hin', 'hinter', 'ich', 'mich', 'mir', 'ihr', 'ihre', 'ihrem', 'ihren', 'ihrer', 'ihres', 'euc

- 한국어 불용어 리스트는 들어있지 않음

In [ ]:
sw_german = stopwords.words('korean')

# 3) 문서 단어 행렬(Document-Term Matrix, DTM)

## 문서 단어 행렬(Document-Term Matrix, DTM)의 표기법

문서 단어 행렬(Document-Term Matrix, DTM): 
- 다수의 문서에서 등장하는 각 단어들의 빈도를 행렬로 표현한 것 
- 각 문서에 대한 BoW를 하나의 행렬로 만든 것으로 생각할 수 있으며, BoW 표현을 다수의 문서에 대해서 행렬로 표현한 것
- 각 문서에서 등장한 단어의 빈도를 행렬의 값으로 표기한다 
- 문서 단어 행렬은 문서들을 서로 비교할 수 있도록 수치화할 수 있다는 점에서 의의를 갖는다

## 문서 단어 행렬(Document-Term Matrix)의 한계

**1) 희소 표현(Sparse representation)** <br/>

원-핫 벡터는 단어 집합의 크기가 벡터의 차원이 되고 대부분의 값이 0이 된다는 특징이 있었다.   <br/>
이 특징은 공간적 낭비와 계산 리소스를 증가시킬 수 있다는 점에서 원-핫 벡터의 단점이였는데, DTM도 마찬가지이다. <br/>
각 문서 벡터의 차원은 원-핫 벡터와 마찬가지로 전체 단어 집합의 크기를 가진다. <br/>
만약 가지고 있는 전체 코퍼스가 방대한 데이터라면 문서 벡터의 차원은 수백만의 차원을 가질 수도 있다. <br/>
또한 많은 문서 벡터가 대부분의 값이 0을 가질 수도 있을 것이다. <br/>
당장 위에서 예로 들었던 문서 단어 행렬의 모든 행이 0이 아닌 값보다 0의 값이 더 많은 것을 볼 수 있다.<br/>

원-핫 벡터나 DTM과 같은 대부분의 값이 0인 표현을 희소 벡터(sparse vector) 또는 희소 행렬(sparse matrix)라고 부르는데, 희소 벡터는 많은 양의 저장 공간과 계산을 위한 리소스를 필요로 한다. <br/>
이러한 이유로 전처리를 통해 단어 집합의 크기를 줄이는 일은 BoW 표현을 사용하는 모델에서 중요할 수 있다. <br/>
앞서 배운 텍스트 전처리 방법을 사용하여 구두점, 빈도수가 낮은 단어, 불용어를 제거하고, 어간이나 표제어 추출을 통해 단어를 정규화하여 단어 집합의 크기를 줄일 수 있다.<br/><br/>



**2) 단순 빈도 수 기반 접근**<br/>
여러 문서에 등장하는 모든 단어에 대해서 빈도 표기를 하는 이런 방법은 때로는 한계를 가진다. <br/>
예를 들어 영어에 대해서 DTM을 만들었을 때, 불용어인 the는 어떤 문서이든 자주 등장할 수 밖에 없다. <br/>
그런데 유사한 문서인지 비교하고 싶은 문서1, 문서2, 문서3에서 동일하게 the가 빈도수가 높다고 해서 이 문서들이 유사한 문서라고 판단해서는 안된다.<br/>

각 문서에는 중요한 단어와 불필요한 단어들이 혼재되어 있다. <br/>
앞서 불용어(stopwords)는 자연어 처리에 있어 의미를 거의 갖지 못하는 단어라고 언급한 바 있다. <br/>
그렇다면 DTM에 불용어와 중요한 단어에 대해서 가중치를 다르게 줄 수 있는 방법은 없을까? <br/>
이를 위해 사용하는 것이 TF-IDF이다.

# 4) TF-IDF(Term Frequency-Inverse Document Frequency)

## TF-IDF(단어 빈도-역 문서 빈도, Term Frequency-Inverse Document Frequency)

TF-IDF(Term Frequency-Inverse Document Frequency):
- 단어의 빈도와 역 문서 빈도(문서의 빈도에 특정 식을 취함)를 사용하여 DTM 내의 각 단어들마다 중요한 정도를 가중치로 주는 방법
- 우선 DTM을 만든 후, TF-IDF 가중치를 부여하여서 값을 구함
- TF-IDF는 주로 문서의 유사도, 검색 시스템에서 검색 결과의 중요도를 정하는 작업, 문서 내에서 특정 단어의 중요도를 구하는 작업 등에 쓰일 수 있다
- TF-IDF는 TF와 IDF를 곱한 값을 의미한다
- 문서를 d, 단어를 t, 문서의 총 개수를 n이라고 표현할 때 TF, DF, IDF는 아래와 같이 정의할 수 있다

**(1) tf(d,t) : 특정 문서 d에서의 특정 단어 t의 등장 횟수.** <br/>
TF는 앞에서 배운 DTM의 예제에서 각 단어들이 가진 값들이다. <br/>
DTM이 각 문서에서의 각 단어의 등장 빈도를 나타내는 값이었기 때문이다.<br/>

**(2) df(t) : 특정 단어 t가 등장한 문서의 수.**<br/>
여기서 특정 단어가 각 문서, 또는 문서들에서 몇 번 등장했는지는 관심가지지 않으며 오직 특정 단어 t가 등장한 문서의 수에만 관심을 가진다. <br/>
앞서 배운 DTM에서 바나나는 문서2와 문서3에서 등장했었다. <br/>
이 경우, 바나나의 df는 2이다. <br/>
문서3에서 바나나가 두 번 등장했지만, 그것은 중요한 게 아니다. <br/>
심지어 바나나란 단어가 문서2에서 100번 등장했고, 문서3에서 200번 등장했다고 하더라도 바나나의 df는 2이다.

**(3) idf(d, t) : df(t)에 반비례하는 수.** <br/><br/>
$idf(d, t) = log(\frac{n}{1+df(t)})$<br/><br/>
IDF라는 이름을 보고 DF의 역수가 아닐까 생각했다면, IDF는 DF의 역수를 취하고 싶은 것이 맞다 <br/>
그런데 log와 분모에 1을 더해주는 식에 의아하실 수 있다. <br/>
log를 사용하지 않았을 때, IDF를 DF의 역수($\frac{n}{df(t)}$라는 식)로 사용한다면 총 문서의 수 n이 커질 수록, IDF의 값은 기하급수적으로 커지게 된다. <br/>
그렇기 때문에 log를 사용하는 것이다.

TF-IDF는 모든 문서에서 자주 등장하는 단어는 중요도가 낮다고 판단하며, 특정 문서에서만 자주 등장하는 단어는 중요도가 높다고 판단한다.
TF-IDF 값이 낮으면 중요도가 낮은 것이며, TF-IDF 값이 크면 중요도가 큰 것이다. 
즉, the나 a와 같이 불용어의 경우에는 모든 문서에 자주 등장하기 마련이기 때문에 자연스럽게 불용어의 TF-IDF의 값은 다른 단어의 TF-IDF에 비해서 낮아지게 된다.

앞서 DTM을 설명하기위해 들었던 위의 예제를 가지고 TF-IDF에 대해 이해해보도록 하자. 
우선 TF는 앞서 사용한 DTM을 그대로 사용하면, 그것이 각 문서에서의 각 단어의 TF가 된다.

그렇다면 이제 구해야할 것은 TF와 곱해야할 값인 IDF이다. 
로그는 자연 로그를 사용하도록 하자. 
자연 로그는 로그의 밑을 자연 상수 e(e=2.718281...)를 사용하는 로그를 말한다. 
IDF 계산을 위해 사용하는 로그의 밑은 TF-IDF를 사용하는 사용자가 임의로 정할 수 있는데, 여기서 로그는 마치 기존의 값에 곱하여 값의 크기를 조절하는 상수의 역할을 한다. 
그런데 보통 각종 프로그래밍 언어나 프로그램에서 패키지로 지원하는 TF-IDF의 로그는 대부분 자연 로그를 사용한다. 
그렇기 때문에 자연 로그를 사용하도록 하겠다. 
자연 로그는 보통 log라고 표현하지 않고, ln이라고 표현한다.

문서의 총 수는 4이기 때문에 ln 안에서 분자는 늘 4으로 동일하다. 
분모의 경우에는 각 단어가 등장한 문서의 수(DF)를 의미하는데, 예를 들어서 '먹고'의 경우에는 총 2개의 문서(문서1, 문서2)에 등장했기 때문에 2라는 값을 가진다. 
각 단어에 대해서 IDF의 값을 비교해보면 문서 1개에만 등장한 단어와 문서 2개에만 등장한 단어는 값의 차이를 보인다. 
IDF는 여러 문서에서 등장한 단어의 가중치를 낮추는 역할을 하기 때문이다.

그러면 이제 TF-IDF를 계산해보도록 하자. 
TF는 DTM을 그대로 가져오면 각 문서에서의 각 단어의 TF를 가져오게 되기 때문에, 앞서 사용한 DTM에서 단어 별로 위의 IDF값을 그대로 곱해주면 TF-IDF가 나오게 된다.

## 사이킷런을 이용한 DTM과 TF-IDF 실습

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

vector = CountVectorizer()

print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


사이킷런은 TF-IDF를 자동 계산해주는 TfidfVectorizer를 제공한다. <br/>
다만, 사이킷런의 TF-IDF는 위에서 배웠던 보편적인 TF-IDF 식에서 좀 더 조정된 다른 식을 사용한다. <br/>
하지만 크게 다른 식은 아니며 여전히 TF-IDF가 가진 의도를 그대로 갖고 있으므로 사이킷런의 TF-IDF를 그대로 사용하셔도 좋다.<br/>
(IDF 계산 시 분자에다가도 1을 더해주며, TF-IDF에 L2 정규화라는 방법으로 값을 조정하는 등의 차이)

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

tfidfv = TfidfVectorizer().fit(corpus)

display(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
